app = "l-agence"

[build]
  dockerfile = "Dockerfile"

[env]
  # Vous pouvez garder PORT si vous le souhaitez, mais il ne sera pas utilisé par le bot Discord
  PORT = "8080" # Ou supprimez-le si non pertinent

# La section [http_service] est supprimée
