name: Deploy to Fly.io

on:
  push:
    branches:
      - master  # ou "master" si c'est ta branche par défaut

jobs:
  deploy:
    name: Deploy app to Fly.io
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Flyctl
        uses: superfly/flyctl-actions/setup-flyctl@master

      - name: Deploy to Fly.io
        run: flyctl deploy --app l-agence --remote-only
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
          FIREBASE_KEY_JSON: ${{ secrets.FIREBASE_KEY_JSON }}
